# #############################################################################
# #############################################################################
# MLB Utilities Executable Programs Make File
# #############################################################################
#
# File Description: Executable programs make file for miscellaneous MLB
#                   utilities.
#
# Revision History: 2008-07-31 --- Creation.
#                       Michael L. Brock
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_BINS	=	\
			CannedPacketConverter		\
			CannedPacketConverterToPCap	\
			CannedPacketDumper		\
			CannedPacketRecv		\
			CannedPacketSend

SRCS		=

include ../.make/MakeSuffix.mk

