# #############################################################################
# #############################################################################
# MLB Utilities Executable Programs Make File
# #############################################################################
#
# File Description: Executable programs make file for miscellaneous MLB
#                   utilities.
#
# Revision History: 2008-07-31 --- Creation.
#                       Michael L. Brock
#
#       Copyright Michael L. Brock 2008 - 2014.
#       Distributed under the Boost Software License, Version 1.0.
#       (See accompanying file LICENSE_1_0.txt or copy at
#       http://www.boost.org/LICENSE_1_0.txt)
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_BINS	=	\
			CannedPacketConverter		\
			CannedPacketConverterToPCap	\
			CannedPacketDumper		\
			CannedPacketRecv		\
			CannedPacketSend

SRCS		=

include ../.make/MakeSuffix.mk

