# #############################################################################
# #############################################################################
# SocketIo Library Make File
# #############################################################################
#
# File Description: SocketIo library make file.
#
# Revision History: 2008-07-31 --- Creation.
#                       Michael L. Brock
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_LIBS	=	libSocketIo.a

TARGET_BINS	=

SRCS		=	\
			IpAddressGeneric.cpp		\
			MulticastIP.cpp			\
			PacketFileReader.cpp		\
			PacketFileWriter.cpp		\
			PacketFormat.cpp		\
			PacketReceiver.cpp		\
			PacketReceiverAsyncMC.cpp	\
			PacketReceiverAsyncMCast.cpp	\
			PacketReceiverMC.cpp		\
			PacketReceiverMCast.cpp		\
			PacketReceiverUdp.cpp		\
			PacketSender.cpp		\
			PacketSenderMC.cpp		\
			PacketSenderMCast.cpp		\
			PacketSenderUdp.cpp		\
			PacketSocket.cpp		\
			PacketSocketAsync.cpp		\
			ResolveHost.cpp			\
			ResolveService.cpp		\
			SocketIoParseCmdLineArg.cpp	\
			SocketSpec.cpp			\
			SocketSpecLocal.cpp		\
			StreamAcceptor.cpp		\
			StreamAcceptorAsync.cpp		\
			StreamSocket.cpp		\
			StreamSocketAsync.cpp		\
			StringToIpAddress.cpp		\
			TimerHandler.cpp

include ../.make/MakeSuffix.mk

