// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpbElementInfoTestTwo_PhoneType.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GpbElementInfoTestTwo_PhoneType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace GpbElementInfoTestTwo {

namespace {

const ::google::protobuf::EnumDescriptor* PhoneType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto() {
  protobuf_AddDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GpbElementInfoTestTwo_PhoneType.proto");
  GOOGLE_CHECK(file != NULL);
  PhoneType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_GpbElementInfoTestTwo_5fPhoneType_2eproto() {
}

void protobuf_AddDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n%GpbElementInfoTestTwo_PhoneType.proto\022"
    "\025GpbElementInfoTestTwo*+\n\tPhoneType\022\n\n\006M"
    "OBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002", 107);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GpbElementInfoTestTwo_PhoneType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GpbElementInfoTestTwo_5fPhoneType_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GpbElementInfoTestTwo_5fPhoneType_2eproto {
  StaticDescriptorInitializer_GpbElementInfoTestTwo_5fPhoneType_2eproto() {
    protobuf_AddDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto();
  }
} static_descriptor_initializer_GpbElementInfoTestTwo_5fPhoneType_2eproto_;
const ::google::protobuf::EnumDescriptor* PhoneType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PhoneType_descriptor_;
}
bool PhoneType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GpbElementInfoTestTwo

// @@protoc_insertion_point(global_scope)
