// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpbElementInfoTestTwo_PhoneType.proto

#ifndef PROTOBUF_GpbElementInfoTestTwo_5fPhoneType_2eproto__INCLUDED
#define PROTOBUF_GpbElementInfoTestTwo_5fPhoneType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace GpbElementInfoTestTwo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto();
void protobuf_AssignDesc_GpbElementInfoTestTwo_5fPhoneType_2eproto();
void protobuf_ShutdownFile_GpbElementInfoTestTwo_5fPhoneType_2eproto();


enum PhoneType {
  MOBILE = 0,
  HOME = 1,
  WORK = 2
};
bool PhoneType_IsValid(int value);
const PhoneType PhoneType_MIN = MOBILE;
const PhoneType PhoneType_MAX = WORK;
const int PhoneType_ARRAYSIZE = PhoneType_MAX + 1;

const ::google::protobuf::EnumDescriptor* PhoneType_descriptor();
inline const ::std::string& PhoneType_Name(PhoneType value) {
  return ::google::protobuf::internal::NameOfEnum(
    PhoneType_descriptor(), value);
}
inline bool PhoneType_Parse(
    const ::std::string& name, PhoneType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PhoneType>(
    PhoneType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace GpbElementInfoTestTwo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::GpbElementInfoTestTwo::PhoneType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GpbElementInfoTestTwo::PhoneType>() {
  return ::GpbElementInfoTestTwo::PhoneType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GpbElementInfoTestTwo_5fPhoneType_2eproto__INCLUDED
