// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpbElementInfoTestTwo_PhoneNumber.proto

#ifndef PROTOBUF_GpbElementInfoTestTwo_5fPhoneNumber_2eproto__INCLUDED
#define PROTOBUF_GpbElementInfoTestTwo_5fPhoneNumber_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "GpbElementInfoTestTwo_PhoneType.pb.h"
// @@protoc_insertion_point(includes)

namespace GpbElementInfoTestTwo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GpbElementInfoTestTwo_5fPhoneNumber_2eproto();
void protobuf_AssignDesc_GpbElementInfoTestTwo_5fPhoneNumber_2eproto();
void protobuf_ShutdownFile_GpbElementInfoTestTwo_5fPhoneNumber_2eproto();

class PhoneNumber;

// ===================================================================

class PhoneNumber : public ::google::protobuf::Message {
 public:
  PhoneNumber();
  virtual ~PhoneNumber();

  PhoneNumber(const PhoneNumber& from);

  inline PhoneNumber& operator=(const PhoneNumber& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PhoneNumber& default_instance();

  void Swap(PhoneNumber* other);

  // implements Message ----------------------------------------------

  PhoneNumber* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PhoneNumber& from);
  void MergeFrom(const PhoneNumber& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string number = 1;
  inline bool has_number() const;
  inline void clear_number();
  static const int kNumberFieldNumber = 1;
  inline const ::std::string& number() const;
  inline void set_number(const ::std::string& value);
  inline void set_number(const char* value);
  inline void set_number(const char* value, size_t size);
  inline ::std::string* mutable_number();
  inline ::std::string* release_number();
  inline void set_allocated_number(::std::string* number);

  // optional .GpbElementInfoTestTwo.PhoneType type = 2 [default = HOME];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::GpbElementInfoTestTwo::PhoneType type() const;
  inline void set_type(::GpbElementInfoTestTwo::PhoneType value);

  // @@protoc_insertion_point(class_scope:GpbElementInfoTestTwo.PhoneNumber)
 private:
  inline void set_has_number();
  inline void clear_has_number();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* number_;
  int type_;
  friend void  protobuf_AddDesc_GpbElementInfoTestTwo_5fPhoneNumber_2eproto();
  friend void protobuf_AssignDesc_GpbElementInfoTestTwo_5fPhoneNumber_2eproto();
  friend void protobuf_ShutdownFile_GpbElementInfoTestTwo_5fPhoneNumber_2eproto();

  void InitAsDefaultInstance();
  static PhoneNumber* default_instance_;
};
// ===================================================================


// ===================================================================

// PhoneNumber

// required string number = 1;
inline bool PhoneNumber::has_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PhoneNumber::set_has_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PhoneNumber::clear_has_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PhoneNumber::clear_number() {
  if (number_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    number_->clear();
  }
  clear_has_number();
}
inline const ::std::string& PhoneNumber::number() const {
  // @@protoc_insertion_point(field_get:GpbElementInfoTestTwo.PhoneNumber.number)
  return *number_;
}
inline void PhoneNumber::set_number(const ::std::string& value) {
  set_has_number();
  if (number_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    number_ = new ::std::string;
  }
  number_->assign(value);
  // @@protoc_insertion_point(field_set:GpbElementInfoTestTwo.PhoneNumber.number)
}
inline void PhoneNumber::set_number(const char* value) {
  set_has_number();
  if (number_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    number_ = new ::std::string;
  }
  number_->assign(value);
  // @@protoc_insertion_point(field_set_char:GpbElementInfoTestTwo.PhoneNumber.number)
}
inline void PhoneNumber::set_number(const char* value, size_t size) {
  set_has_number();
  if (number_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    number_ = new ::std::string;
  }
  number_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:GpbElementInfoTestTwo.PhoneNumber.number)
}
inline ::std::string* PhoneNumber::mutable_number() {
  set_has_number();
  if (number_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    number_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:GpbElementInfoTestTwo.PhoneNumber.number)
  return number_;
}
inline ::std::string* PhoneNumber::release_number() {
  clear_has_number();
  if (number_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = number_;
    number_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PhoneNumber::set_allocated_number(::std::string* number) {
  if (number_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete number_;
  }
  if (number) {
    set_has_number();
    number_ = number;
  } else {
    clear_has_number();
    number_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:GpbElementInfoTestTwo.PhoneNumber.number)
}

// optional .GpbElementInfoTestTwo.PhoneType type = 2 [default = HOME];
inline bool PhoneNumber::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PhoneNumber::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PhoneNumber::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PhoneNumber::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::GpbElementInfoTestTwo::PhoneType PhoneNumber::type() const {
  // @@protoc_insertion_point(field_get:GpbElementInfoTestTwo.PhoneNumber.type)
  return static_cast< ::GpbElementInfoTestTwo::PhoneType >(type_);
}
inline void PhoneNumber::set_type(::GpbElementInfoTestTwo::PhoneType value) {
  assert(::GpbElementInfoTestTwo::PhoneType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:GpbElementInfoTestTwo.PhoneNumber.type)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GpbElementInfoTestTwo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GpbElementInfoTestTwo_5fPhoneNumber_2eproto__INCLUDED
