# #############################################################################
# #############################################################################
# SockLibX Library Make File
# #############################################################################
#
# File Description: SockLibX library make file.
#
# Revision History: 2000-01-13 --- Creation.
#                       Michael L. Brock
#
#       Copyright Michael L. Brock 2000 - 2014.
#       Distributed under the Boost Software License, Version 1.0.
#       (See accompanying file LICENSE_1_0.txt or copy at
#       http://www.boost.org/LICENSE_1_0.txt)
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_LIBS	=	libSockLibX.a

TARGET_BINS	=

SRCS		=	\
			accept.cpp					\
			AddressIP.cpp					\
			addrinet.cpp					\
			bind.cpp					\
			ckhentp.cpp					\
			ckpentp.cpp					\
			cksentp.cpp					\
			cksock.cpp					\
			cleanup.cpp					\
			close.cpp					\
			connect.cpp					\
			cphent.cpp					\
			cppent.cpp					\
			cpsent.cpp					\
			EndPointIP.cpp					\
			errortxt.cpp					\
			exphostl.cpp					\
			exphosts.cpp					\
			frhent.cpp					\
			frpent.cpp					\
			frsent.cpp					\
			gethent.cpp					\
			gethentb.cpp					\
			getmac.cpp					\
			getpent.cpp					\
			getpentb.cpp					\
			getpname.cpp					\
			getsent.cpp					\
			getsentb.cpp					\
			getsname.cpp					\
			getsopt.cpp					\
			hostname.cpp					\
			inetaddr.cpp					\
			inhent.cpp					\
			inpent.cpp					\
			insent.cpp					\
			lenshent.cpp					\
			lenspent.cpp					\
			lenssent.cpp					\
			listen.cpp					\
			npsli.cpp					\
			recv.cpp					\
			recvfrom.cpp					\
			rslvhost.cpp					\
			rslvhsp.cpp					\
			rslvprot.cpp					\
			rslvserv.cpp					\
			select.cpp					\
			send.cpp					\
			sendto.cpp					\
			ServerX.cpp					\
			setbmode.cpp					\
			setsopt.cpp					\
			shutdown.cpp					\
			socket.cpp					\
			SocketMC.cpp					\
			SocketSpec.cpp					\
			SocketX.cpp					\
			SockLibX.cpp					\
			SockLibXConnectFailure.cpp			\
			SockLibXConnectRefused.cpp			\
			SockLibXConnectTimeOut.cpp			\
			SockLibXContext.cpp				\
			SockLibXException.cpp				\
			SockLibXExceptionError.cpp			\
			SockLibXParseCmdLineArg.cpp			\
			SockLibXPeerClosed.cpp				\
			SockLibXTimeOut.cpp				\
			startup.cpp					\
			support.cpp

include ../.make/MakeSuffix.mk

