# #############################################################################
# #############################################################################
# Library Make File
# #############################################################################
#
# File Description: LbmWrapper library make file.
#
# Revision History: 2008-08-17 --- Creation.
#                       Michael L. Brock
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_LIBS	=	libLbmWrapper.a

TARGET_BINS	=

SRCS		=	\
			LbmAttrSupport.cpp				\
			LbmContext.cpp					\
			LbmEventQueue.cpp				\
			LbmException.cpp				\
			LbmExceptionStatus.cpp				\
			LbmLogSupport.cpp				\
			LbmMiscSupport.cpp				\
			LbmRcv.cpp					\
			LbmSrc.cpp					\
			LbmStatsContext.cpp				\
			LbmStatsEventQueue.cpp				\
			LbmStatsRcv.cpp					\
			LbmStatsSrc.cpp					\
			LbmTopicRcv.cpp					\
			LbmTopicSrc.cpp					\
			LbmWildcardRcv.cpp

include ../.make/MakeSuffix.mk

