# #############################################################################
# #############################################################################
# XercesUtils Library Make File
# #############################################################################
#
# File Description: XercesUtils library make file.
#
# Revision History: 2005-01-08 --- Creation.
#                       Michael L. Brock
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_LIBS	=	libXercesUtils.a

TARGET_BINS	=

SRCS		=	\
			XercesContext.cpp			\
			XmlDomElement.cpp			\
			XmlStringToString.cpp

include ../.make/MakeSuffix.mk

