# #############################################################################
# #############################################################################
# XercesUtils Library Make File
# #############################################################################
#
# File Description: XercesUtils library make file.
#
# Revision History: 2005-01-08 --- Creation.
#                       Michael L. Brock
#
#       Copyright Michael L. Brock 2005 - 2014.
#       Distributed under the Boost Software License, Version 1.0.
#       (See accompanying file LICENSE_1_0.txt or copy at
#       http://www.boost.org/LICENSE_1_0.txt)
#
# #############################################################################

include ../.make/MakePrefix.mk

TARGET_LIBS	=	libXercesUtils.a

TARGET_BINS	=

SRCS		=	\
			XercesContext.cpp			\
			XmlDomElement.cpp			\
			XmlStringToString.cpp

include ../.make/MakeSuffix.mk

